### ISSUE TITLE
Примитивный дизайн

### ISSUE THREAD

**Issue by TonitaN** [Qmask26/converter_team_project#27]
Герман и Поршенко пока так и не появлялись. Есть такое предложение: по факту я буду оценивать работу только тех участников, кто уже внёс вклад (поскольку за Германа вынуждены реализовывать функционал другие), а дизайн упрощайте до максимума (тупо печатать автомат в графвизе и ответы на предикаты в выходной поток). Владимира, раз он сыграл в человека-невидимку, отправим делать индивидуальную лабораторную работу, а Егор пусть сам решает - будет он делать потом дизайн (со штрафом), или индивидуальный вариант.

**Comment by Qmask26** [comment]
Герман в процессе, просто пул реквесты еще не делал
